spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dpms
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

security:
  jwt:
    issuer: dpms
    secret: ${JWT_SECRET}
    accessTokenMinutes: 60

server:
  port: 8081

app:
  cors:
    allowedOrigins:
      - "http://localhost:3000"
      - "http://localhost:5173"
logging:
  level:
    org.springframework.security: DEBUG