spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dpms
    username: dpms
    password: dpms

security:
  jwt:
    issuer: dpms
    secret: "ole si brahim yoyoyooyoyo 20252026@@@@"
    accessTokenMinutes: 60

server:
  port: 8081

app:
  cors:
    allowedOrigins:
      - "http://localhost:3000"
      - "http://localhost:5173"
logging:
  level:
    org.springframework.security: DEBUG