spring:
  application:
    name: dental-management-system-be
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5433/dpms
    username: dpms
    password: dpms

server:
  port: 8081
security:
  jwt:
    issuer: dpms
    secret: "ole si brahim ole ole GG kafo wala magasart"
    accessTokenMinutes: 60

app:
  cors:
    allowedOrigins:
      - "http://localhost:3000"
      - "http://localhost:5173"
